common: &common
  adapter: postgresql
  encoding: unicode
  username: tyler
  password: 123456
  pool: 5

development:
  <<: *common
  database: rails_setup_dev

test:
  <<: *common
  database: rails_setup_test